remote_theme: jekyll/minima
title: TG-TRENDS
description: Tracking Trends and Insights - Khag Budgam
github:
  is_project_page: true
  project_title: TG-TRENDS
url: https://stasaduq90-code.github.io/TG-TRENDS-
baseurl: /TG-TRENDS-
